name: dotnet-script test
on: [push, pull_request]
jobs:
  build_nix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - run: printenv 
    - name: Print commits with git rev-list --count HEAD
      run: echo $(git rev-list --count HEAD)
    - name: Print commits with git log --pretty=format:'' | wc -l 
      run: git log --pretty=format:'' | wc -l
    - name: dotnet-script example
      uses: docker://andmos/dotnet-script:latest
      with:
        args: --version
